# Generated by Django 4.1.4 on 2022-12-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('genre', models.CharField(choices=[('Аниме', 'Аниме'), ('Сёнен', 'Сёнен'), ('Сёнен-ай', 'Сёнен-ай'), ('Сэнтай', 'Сэнтай'), ('Сёдзё', 'Сёдзё'), ('Сэйнэн', 'Сэйнэн'), ('Дзёсэй', 'Дзёсэй')], max_length=200)),
            ],
        ),
    ]
