# Generated by Django 4.1.4 on 2022-12-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(choices=[('Аниме', 'Аниме'), ('Сёнен', 'Сёнен'), ('Сёнен-ай', 'Сёнен-ай'), ('Сэнтай', 'Сэнтай'), ('Сёдзё', 'Сёдзё'), ('Сэйнэн', 'Сэйнэн'), ('Дзёсэй', 'Дзёсэй'), ('Комедия', 'Комедия'), ('Пародия', 'Пародия'), ('Романтика', 'Романтика'), ('Мыльная опера', 'Мыльная опера'), ('Школьная мыльная опера', 'Школьная мыльная опера'), ('Гарем', 'Гарем')], max_length=200),
        ),
    ]
